#!/usr/bin/env python3
"""
从 https://models.dev/api.json 获取 LLM 价格数据,
生成 internal/price/catalog/presets.go 文件。

filter_models 为纯函数, 接收原始 JSON 数据并返回过滤后的 (model_id, cost) 列表,
可与 Go 侧 filterDeveloperPrices 用同一 fixture 做等价测试, 无网络依赖。
"""

import json
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

LLM_PRICE_URL = "https://models.dev/api.json"

# 研发商及其自研模型系列前缀, 过滤同一平台提供的第三方模型。
# 须与 internal/price/price.go 的 developerFamilies 保持一致。
DEVELOPERS: dict[str, tuple[str, ...]] = {
    "openai": ("gpt", "o"),
    "anthropic": ("claude",),
    "google": ("gemini", "gemma", "lyria", "veo"),
    "deepseek": ("deepseek",),
    "xai": ("grok",),
    "alibaba": ("qwen", "qvq"),
    "zhipuai": ("glm",),
    "minimax": ("minimax",),
    "moonshotai": ("kimi",),
    "v0": ("v0",),
    "xiaomi": ("mimo",),
}

PRESETS_GO_TEMPLATE = """package catalog

// Code generated by scripts/updatePrice.py. DO NOT EDIT.
// Last updated: {update_time}

import "github.com/bestruirui/octopus/internal/model"

var presetPrices = map[string]model.LLMPrice{{
{entries}
}}
"""


def fetch_price_data() -> dict:
    """从 API 获取价格数据"""
    req = urllib.request.Request(
        LLM_PRICE_URL,
        headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
        },
    )
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read().decode("utf-8"))


def format_price(value: float | None) -> str:
    """格式化价格值, 去除不必要的尾部零"""
    if value is None:
        return "0"
    if value == 0:
        return "0"
    formatted = f"{value:.10f}".rstrip("0").rstrip(".")
    return formatted


def generate_entry(model_id: str, cost: dict) -> str:
    """生成单个模型的 Go map entry"""
    input_price = format_price(cost.get("input"))
    output_price = format_price(cost.get("output"))
    cache_read = format_price(cost.get("cache_read"))
    cache_write = format_price(cost.get("cache_write"))
    return f'\t"{model_id}": {{Input: {input_price}, Output: {output_price}, CacheRead: {cache_read}, CacheWrite: {cache_write}}},'


def _valid_price(v: float) -> bool:
    """价格值有效: 非负且有限(非 NaN/Inf)。须与 Go 侧 validPrice 一致。"""
    import math

    return v is not None and v >= 0 and math.isfinite(v)


def validate_cost(cost: dict | None) -> tuple[dict, bool]:
    """验证 cost 字段并返回规范化 dict, 与 Go 侧 validateCost 语义一致。

    cost 缺失/None → 拒绝(未知≠免费); input/output 缺失/无效 → 拒绝;
    显式 input=0/output=0 → 合法免费; cache_read/cache_write 缺失 → 0, 存在则须有效;
    所有值须 >=0 且有限, negative/NaN/Inf 拒绝。返回 (normalized_cost, ok)。
    """
    if cost is None:
        return {}, False
    inp = cost.get("input")
    out = cost.get("output")
    if inp is None or out is None:
        return {}, False
    if not _valid_price(inp) or not _valid_price(out):
        return {}, False
    result = {"input": inp, "output": out}
    cache_read = cost.get("cache_read")
    if cache_read is not None:
        if not _valid_price(cache_read):
            return {}, False
        result["cache_read"] = cache_read
    cache_write = cost.get("cache_write")
    if cache_write is not None:
        if not _valid_price(cache_write):
            return {}, False
        result["cache_write"] = cache_write
    return result, True


def filter_models(raw_price: dict) -> list[tuple[str, dict]]:
    """从原始价格数据中按研发商过滤自研文本输出模型, 返回 (model_id, validated_cost) 列表。

    纯函数: 不访问网络, 接收已解析的 dict, 可用固定 fixture 做等价测试。
    过滤+验证规则须与 Go 侧 filterDeveloperPrices + validateCost 一致:
      - model_id 非空
      - model_family 以研发商自研前缀开头
      - output 含 "text"
      - model_id / model_family 不含 "embed"
      - cost 缺失/null 或 input/output 缺失/无效 → 拒绝(不作为 known free)
      - 显式 input=0/output=0 → 合法免费
      - cache_read/cache_write 缺失 → 0, 存在则须有效
      - negative/NaN/Inf → 拒绝
    """
    entries: list[tuple[str, dict]] = []
    generated_model_ids: set[str] = set()
    for provider, family_prefixes in DEVELOPERS.items():
        if provider not in raw_price:
            continue
        models = raw_price[provider].get("models", {})
        for model_data in models.values():
            model_id = model_data.get("id", "").lower()
            model_family = model_data.get("family", "").lower()
            output_modalities = model_data.get("modalities", {}).get("output", [])
            cost = model_data.get("cost")
            if (
                not model_id
                or not model_family.startswith(family_prefixes)
                or "text" not in output_modalities
                or "embed" in model_id
                or "embed" in model_family
            ):
                continue
            validated, ok = validate_cost(cost)
            if not ok:
                continue
            if model_id in generated_model_ids:
                raise ValueError(
                    f"Duplicate model ID after developer filtering: {model_id}"
                )
            entries.append((model_id, validated))
            generated_model_ids.add(model_id)
    return entries


def main() -> None:
    print(f"Fetching price data from {LLM_PRICE_URL}...")
    raw_price = fetch_price_data()
    filtered = filter_models(raw_price)

    entries = []
    model_count = 0
    provider_counts: dict[str, int] = {}
    for model_id, cost in filtered:
        entries.append(generate_entry(model_id, cost))
        model_count += 1
        provider = model_id.split("-", 1)[0] if "-" in model_id else model_id
        provider_counts[provider] = provider_counts.get(provider, 0) + 1

    update_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    content = PRESETS_GO_TEMPLATE.format(
        update_time=update_time,
        entries="\n".join(entries),
    )

    script_dir = Path(__file__).parent
    output_path = script_dir.parent / "internal" / "price" / "catalog" / "presets.go"
    output_path.write_text(content, encoding="utf-8")
    print(f"\nGenerated {output_path} with {model_count} models")


if __name__ == "__main__":
    main()
